name: production
protection_rules:
  - type: required_reviewers
    required_reviewers: 2
    dismiss_stale_reviews: true
  - type: wait_timer
    wait_timer: 5
  - type: required_status_checks
    required_status_checks:
      - context: "CI/CD Pipeline"
      - context: "Performance Budget"
      - context: "Security Scan"
  - type: deployment_branch_policy
    deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false

secrets:
  - name: VERCEL_TOKEN
    description: "Vercel deployment token"
  - name: VERCEL_ORG_ID
    description: "Vercel organization ID"
  - name: VERCEL_PROJECT_ID
    description: "Vercel project ID"
  - name: OPENAI_API_KEY
    description: "OpenAI API key for AI features"
  - name: DATABASE_URL
    description: "Production database connection string"
  - name: AWS_ROLE_ARN
    description: "AWS IAM role for secrets management"
  - name: SLACK_WEBHOOK
    description: "Slack webhook for notifications"
